### model
model_name_or_path: google/gemma-3-12b-it
adapter_name_or_path: saves/gemma3-12b-it1/lora/sft
template: gemma3
trust_remote_code: true

### export
export_dir: output/gemma3-12b-it1
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false